// React/entrypoints/popup/components/LocalModelPage.vue
<template>
  <div class="local-model-page">
    <!-- Back Button -->
    <div class="page-header">
      <button class="back-button" @click="$emit('back')" title="Back to Home">
        <svg
          viewBox="0 0 24 24"
          width="20"
          height="20"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
        </svg>
        <span>Back</span>
      </button>
      <h2 class="page-title">Local Models</h2>
    </div>

    <div class="page-content">
      <!-- Semantic Engine -->
      <div class="section">
        <h3 class="section-title">{{ getMessage('semanticEngineLabel') }}</h3>
        <div class="semantic-engine-card">
          <div class="semantic-engine-status">
            <div class="status-info">
              <span :class="['status-dot', getSemanticEngineStatusClass()]"></span>
              <span class="status-text">{{ getSemanticEngineStatusText() }}</span>
            </div>
            <div v-if="semanticEngineLastUpdated" class="status-timestamp">
              {{ getMessage('lastUpdatedLabel') }}
              {{ new Date(semanticEngineLastUpdated).toLocaleTimeString() }}
            </div>
          </div>

          <ProgressIndicator
            v-if="isSemanticEngineInitializing"
            :visible="isSemanticEngineInitializing"
            :text="semanticEngineInitProgress"
            :showSpinner="true"
          />

          <button
            class="primary-action-button"
            :disabled="isSemanticEngineInitializing"
            @click="$emit('initializeSemanticEngine')"
          >
            <BoltIcon />
            <span>{{ getSemanticEngineButtonText() }}</span>
          </button>
        </div>
      </div>

      <!-- Embedding Model Selection -->
      <div class="section">
        <h3 class="section-title">{{ getMessage('embeddingModelLabel') }}</h3>

        <ProgressIndicator
          v-if="isModelSwitching || isModelDownloading"
          :visible="isModelSwitching || isModelDownloading"
          :text="progressText"
          :showSpinner="true"
        />

        <div v-if="modelInitializationStatus === 'error'" class="error-card">
          <div class="error-content">
            <div class="error-icon">⚠️</div>
            <div class="error-details">
              <p class="error-title">{{ getMessage('semanticEngineInitFailedStatus') }}</p>
              <p class="error-message">{{
                modelErrorMessage || getMessage('semanticEngineInitFailedStatus')
              }}</p>
              <p class="error-suggestion">{{ errorTypeText }}</p>
            </div>
          </div>
          <button
            class="retry-button"
            @click="$emit('retryModelInitialization')"
            :disabled="isModelSwitching || isModelDownloading"
          >
            <span>🔄</span>
            <span>{{ getMessage('retryButton') }}</span>
          </button>
        </div>

        <div class="model-list">
          <div
            v-for="model in availableModels"
            :key="model.preset"
            :class="[
              'model-card',
              {
                selected: currentModel === model.preset,
                disabled: isModelSwitching || isModelDownloading,
              },
            ]"
            @click="!isModelSwitching && !isModelDownloading && $emit('switchModel', model.preset)"
          >
            <div class="model-header">
              <div class="model-info">
                <p class="model-name" :class="{ 'selected-text': currentModel === model.preset }">
                  {{ model.preset }}
                </p>
                <p class="model-description">{{ getModelDescription(model) }}</p>
              </div>
              <div v-if="currentModel === model.preset" class="check-icon">
                <CheckIcon class="text-white" />
              </div>
            </div>
            <div class="model-tags">
              <span class="model-tag performance">{{ getPerformanceText(model.performance) }}</span>
              <span class="model-tag size">{{ model.size }}</span>
              <span class="model-tag dimension">{{ model.dimension }}D</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Index Data Management -->
      <div class="section">
        <h3 class="section-title">{{ getMessage('indexDataManagementLabel') }}</h3>
        <div class="stats-grid">
          <div class="stats-card">
            <div class="stats-header">
              <p class="stats-label">{{ getMessage('indexedPagesLabel') }}</p>
              <span class="stats-icon violet">
                <DocumentIcon />
              </span>
            </div>
            <p class="stats-value">{{ storageStats?.indexedPages || 0 }}</p>
          </div>

          <div class="stats-card">
            <div class="stats-header">
              <p class="stats-label">{{ getMessage('indexSizeLabel') }}</p>
              <span class="stats-icon teal">
                <DatabaseIcon />
              </span>
            </div>
            <p class="stats-value">{{ formatIndexSize() }}</p>
          </div>

          <div class="stats-card">
            <div class="stats-header">
              <p class="stats-label">{{ getMessage('activeTabsLabel') }}</p>
              <span class="stats-icon blue">
                <TabIcon />
              </span>
            </div>
            <p class="stats-value">{{ storageStats?.totalTabs || 0 }}</p>
          </div>

          <div class="stats-card">
            <div class="stats-header">
              <p class="stats-label">{{ getMessage('vectorDocumentsLabel') }}</p>
              <span class="stats-icon green">
                <VectorIcon />
              </span>
            </div>
            <p class="stats-value">{{ storageStats?.totalDocuments || 0 }}</p>
          </div>
        </div>

        <ProgressIndicator
          v-if="isClearingData && clearDataProgress"
          :visible="isClearingData"
          :text="clearDataProgress"
          :showSpinner="true"
        />

        <button
          class="danger-action-button"
          :disabled="isClearingData"
          @click="$emit('showClearConfirmation')"
        >
          <TrashIcon />
          <span>{{
            isClearingData ? getMessage('clearingStatus') : getMessage('clearAllDataButton')
          }}</span>
        </button>
      </div>

      <!-- Model Cache Management -->
      <ModelCacheManagement
        :cache-stats="cacheStats"
        :is-managing-cache="isManagingCache"
        @cleanup-cache="$emit('cleanupCache')"
        @clear-all-cache="$emit('clearAllCache')"
      />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { getMessage } from '@/utils/i18n';
import ProgressIndicator from './ProgressIndicator.vue';
import ModelCacheManagement from './ModelCacheManagement.vue';
import {
  DocumentIcon,
  DatabaseIcon,
  BoltIcon,
  TrashIcon,
  CheckIcon,
  TabIcon,
  VectorIcon,
} from './icons';

interface Props {
  // Semantic Engine
  semanticEngineStatus: 'idle' | 'initializing' | 'ready' | 'error';
  isSemanticEngineInitializing: boolean;
  semanticEngineInitProgress: string;
  semanticEngineLastUpdated: number | null;
  // Models
  availableModels: Array<{
    preset: string;
    performance: string;
    size: string;
    dimension: number;
  }>;
  currentModel: string | null;
  isModelSwitching: boolean;
  isModelDownloading: boolean;
  modelDownloadProgress: number;
  modelInitializationStatus: string;
  modelErrorMessage: string;
  modelErrorType: string;
  // Storage Stats
  storageStats: {
    indexedPages: number;
    totalDocuments: number;
    totalTabs: number;
    indexSize: number;
    isInitialized: boolean;
  } | null;
  isClearingData: boolean;
  clearDataProgress: string;
  // Cache
  cacheStats: any;
  isManagingCache: boolean;
}

const props = defineProps<Props>();

defineEmits<{
  (e: 'back'): void;
  (e: 'initializeSemanticEngine'): void;
  (e: 'switchModel', preset: string): void;
  (e: 'retryModelInitialization'): void;
  (e: 'showClearConfirmation'): void;
  (e: 'cleanupCache'): void;
  (e: 'clearAllCache'): void;
}>();

// Computed properties
const getSemanticEngineStatusClass = () => {
  switch (props.semanticEngineStatus) {
    case 'ready':
      return 'bg-emerald-500';
    case 'initializing':
      return 'bg-yellow-500';
    case 'error':
      return 'bg-red-500';
    case 'idle':
    default:
      return 'bg-gray-500';
  }
};

const getSemanticEngineStatusText = () => {
  switch (props.semanticEngineStatus) {
    case 'ready':
      return getMessage('semanticEngineReadyStatus');
    case 'initializing':
      return getMessage('semanticEngineInitializingStatus');
    case 'error':
      return getMessage('semanticEngineInitFailedStatus');
    case 'idle':
    default:
      return getMessage('semanticEngineNotInitStatus');
  }
};

const getSemanticEngineButtonText = () => {
  switch (props.semanticEngineStatus) {
    case 'ready':
      return getMessage('reinitializeButton');
    case 'initializing':
      return getMessage('initializingStatus');
    case 'error':
      return getMessage('reinitializeButton');
    case 'idle':
    default:
      return getMessage('initSemanticEngineButton');
  }
};

const progressText = computed(() => {
  if (props.isModelDownloading) {
    return getMessage('downloadingModelStatus', [props.modelDownloadProgress.toString()]);
  } else if (props.isModelSwitching) {
    return getMessage('switchingModelStatus');
  }
  return '';
});

const errorTypeText = computed(() => {
  switch (props.modelErrorType) {
    case 'network':
      return getMessage('networkErrorMessage');
    case 'file':
      return getMessage('modelCorruptedErrorMessage');
    case 'unknown':
    default:
      return getMessage('unknownErrorMessage');
  }
});

const getModelDescription = (model: any) => {
  switch (model.preset) {
    case 'multilingual-e5-small':
      return getMessage('lightweightModelDescription');
    case 'multilingual-e5-base':
      return getMessage('betterThanSmallDescription');
    default:
      return getMessage('multilingualModelDescription');
  }
};

const getPerformanceText = (performance: string) => {
  switch (performance) {
    case 'fast':
      return getMessage('fastPerformance');
    case 'balanced':
      return getMessage('balancedPerformance');
    case 'accurate':
      return getMessage('accuratePerformance');
    default:
      return performance;
  }
};

const formatIndexSize = () => {
  if (!props.storageStats?.indexSize) return '0 MB';
  const sizeInMB = Math.round(props.storageStats.indexSize / (1024 * 1024));
  return `${sizeInMB} MB`;
};
</script>

<style scoped>
.local-model-page {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.page-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px 20px;
  border-bottom: 1px solid var(--ac-border, #e7e5e4);
  background: var(--ac-surface, #ffffff);
}

.back-button {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 8px 12px;
  background: var(--ac-surface-muted, #f2f0eb);
  border: none;
  border-radius: var(--ac-radius-button, 8px);
  color: var(--ac-text-muted, #6e6e6e);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all var(--ac-motion-fast, 120ms) ease;
}

.back-button:hover {
  background: var(--ac-hover-bg, #f5f5f4);
  color: var(--ac-text, #1a1a1a);
}

.page-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--ac-text, #1a1a1a);
  margin: 0;
}

.page-content {
  flex: 1;
  overflow-y: auto;
  padding: 16px 20px;
}

.section {
  margin-bottom: 24px;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--ac-text, #374151);
  margin-bottom: 12px;
}

.semantic-engine-card {
  background: var(--ac-surface, white);
  border-radius: var(--ac-radius-card, 12px);
  box-shadow: var(--ac-shadow-card, 0 1px 3px rgba(0, 0, 0, 0.08));
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.semantic-engine-status {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.status-info {
  display: flex;
  align-items: center;
  gap: 8px;
}

.status-dot {
  height: 8px;
  width: 8px;
  border-radius: 50%;
}

.status-dot.bg-emerald-500 {
  background-color: #10b981;
}
.status-dot.bg-yellow-500 {
  background-color: #eab308;
}
.status-dot.bg-red-500 {
  background-color: #ef4444;
}
.status-dot.bg-gray-500 {
  background-color: #6b7280;
}

.status-text {
  font-size: 14px;
  font-weight: 500;
  color: var(--ac-text, #1a1a1a);
}

.status-timestamp {
  font-size: 12px;
  color: var(--ac-text-subtle, #9ca3af);
}

.primary-action-button {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: var(--ac-accent, #d97757);
  color: var(--ac-accent-contrast, white);
  font-weight: 600;
  padding: 12px 16px;
  border-radius: var(--ac-radius-button, 8px);
  border: none;
  cursor: pointer;
  transition: all var(--ac-motion-fast, 120ms) ease;
}

.primary-action-button:hover:not(:disabled) {
  background: var(--ac-accent-hover, #c4664a);
}

.primary-action-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.danger-action-button {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: var(--ac-surface, white);
  border: 1px solid var(--ac-border, #d1d5db);
  color: var(--ac-text, #374151);
  font-weight: 600;
  padding: 12px 16px;
  border-radius: var(--ac-radius-button, 8px);
  cursor: pointer;
  transition: all var(--ac-motion-fast, 120ms) ease;
  margin-top: 12px;
}

.danger-action-button:hover:not(:disabled) {
  border-color: #ef4444;
  color: #dc2626;
}

.danger-action-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

/* Model List */
.model-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

/* ... */

/* Stats Grid */
.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

/* ... */

/* Error Card */
.error-card {
  background: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: var(--ac-radius-card, 12px);
  padding: 16px;
  margin-bottom: 16px;
  display: flex;
  align-items: flex-start;
  gap: 16px;
}

.error-content {
  flex: 1;
  display: flex;
  align-items: flex-start;
  gap: 12px;
}

.error-icon {
  font-size: 20px;
  flex-shrink: 0;
}

.error-details {
  flex: 1;
}

.error-title {
  font-size: 14px;
  font-weight: 600;
  color: #dc2626;
  margin: 0 0 4px 0;
}

.error-message {
  font-size: 14px;
  color: #991b1b;
  margin: 0 0 8px 0;
  font-weight: 500;
}

.error-suggestion {
  font-size: 13px;
  color: #7f1d1d;
  margin: 0;
  line-height: 1.4;
}

.retry-button {
  display: flex;
  align-items: center;
  gap: 6px;
  background: #dc2626;
  color: white;
  font-weight: 600;
  padding: 8px 16px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
  transition: all var(--ac-motion-fast, 120ms) ease;
  font-size: 14px;
  flex-shrink: 0;
}

.retry-button:hover:not(:disabled) {
  background: #b91c1c;
}

.retry-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// extension/entrypoints/popup/components/LocalModelPage.tsx
import React, { useMemo } from 'react';
import { getMessage } from '@/utils/i18n';
import ProgressIndicator from './ProgressIndicator';
import ModelCacheManagement, { CacheStats } from './ModelCacheManagement';
import {
    DocumentIcon,
    DatabaseIcon,
    BoltIcon,
    TrashIcon,
    CheckIcon,
    TabIcon,
    VectorIcon,
    RefreshIcon,
} from './icons';

interface ModelDefinition {
    preset: string;
    performance: string;
    size: string;
    dimension: number;
}

interface StorageStats {
    indexedPages: number;
    totalDocuments: number;
    totalTabs: number;
    indexSize: number;
    isInitialized: boolean;
}

interface LocalModelPageProps {
    // Semantic Engine
    semanticEngineStatus: 'idle' | 'initializing' | 'ready' | 'error';
    isSemanticEngineInitializing: boolean;
    semanticEngineInitProgress: string;
    semanticEngineLastUpdated: number | null;
    // Models
    availableModels: ModelDefinition[];
    currentModel: string | null;
    isModelSwitching: boolean;
    isModelDownloading: boolean;
    modelDownloadProgress: number;
    modelInitializationStatus: string;
    modelErrorMessage: string;
    modelErrorType: string;
    // Storage Stats
    storageStats: StorageStats | null;
    isClearingData: boolean;
    clearDataProgress: string;
    // Cache
    cacheStats: CacheStats | null;
    isManagingCache: boolean;

    // Events
    onBack: () => void;
    onInitializeSemanticEngine: () => void;
    onSwitchModel: (preset: string) => void;
    onRetryModelInitialization: () => void;
    onShowClearConfirmation: () => void;
    onCleanupCache: () => void;
    onClearAllCache: () => void;
}

const LocalModelPage: React.FC<LocalModelPageProps> = (props) => {
    const {
        semanticEngineStatus,
        isSemanticEngineInitializing,
        semanticEngineInitProgress,
        semanticEngineLastUpdated,
        availableModels,
        currentModel,
        isModelSwitching,
        isModelDownloading,
        modelDownloadProgress,
        modelInitializationStatus,
        modelErrorMessage,
        modelErrorType,
        storageStats,
        isClearingData,
        clearDataProgress,
        cacheStats,
        isManagingCache,
        onBack,
        onInitializeSemanticEngine,
        onSwitchModel,
        onRetryModelInitialization,
        onShowClearConfirmation,
        onCleanupCache,
        onClearAllCache
    } = props;

    const getSemanticEngineStatusClass = () => {
        switch (semanticEngineStatus) {
            case 'ready': return 'bg-[#10b981]'; // bg-emerald-500
            case 'initializing': return 'bg-[#f59e0b]'; // bg-amber-500
            case 'error': return 'bg-[#ef4444]'; // bg-rose-500
            case 'idle':
            default: return 'bg-[#94a3b8]'; // bg-slate-400
        }
    };

    const getSemanticEngineStatusText = () => {
        switch (semanticEngineStatus) {
            case 'ready': return getMessage('semanticEngineReadyStatus');
            case 'initializing': return getMessage('semanticEngineInitializingStatus');
            case 'error': return getMessage('semanticEngineInitFailedStatus');
            case 'idle':
            default: return getMessage('semanticEngineNotInitStatus');
        }
    };

    const progressText = useMemo(() => {
        if (isModelDownloading) {
            return getMessage('downloadingModelStatus', [modelDownloadProgress.toString()]);
        } else if (isModelSwitching) {
            return getMessage('switchingModelStatus');
        }
        return '';
    }, [isModelDownloading, modelDownloadProgress, isModelSwitching]);

    const formatIndexSize = () => {
        if (!storageStats?.indexSize) return '0 MB';
        const sizeInMB = Math.round(storageStats.indexSize / (1024 * 1024));
        return `${sizeInMB} MB`;
    };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: '#f8fafc', overflow: 'hidden' }}>
            {/* Page Header */}
            <div className="flex items-center gap-3 p-4 bg-white border-b border-[#f1f5f9] shrink-0 z-10">
                <button
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-[#f8fafc] border border-[#e2e8f0] rounded-[8px] text-[#64748b] text-[13px] font-bold hover:bg-[#f1f5f9] hover:text-[#0f172a] transition-all"
                    onClick={onBack}
                >
                    <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="3">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                    </svg>
                    <span>Back</span>
                </button>
                <h2 className="text-[17px] font-[900] text-[#0f172a] tracking-tight m-0 uppercase">Local Models</h2>
            </div>

            {/* Page Content */}
            <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-8 pb-10">

                {/* Semantic Engine Section */}
                <section>
                    <h3 className="text-[11px] font-[900] text-[#94a3b8] uppercase tracking-[0.1em] mb-2.5 ml-1">{getMessage('semanticEngineLabel')}</h3>
                    <div className="bg-white border border-[#e2e8f0] rounded-[16px] shadow-sm p-5">
                        <div className="flex items-center gap-3">
                            <span className={`w-2 h-2 rounded-full ${getSemanticEngineStatusClass()} shadow-sm`}></span>
                            <span className="text-[14px] font-[800] text-[#1e293b]">{getSemanticEngineStatusText()}</span>
                        </div>
                        {semanticEngineLastUpdated && (
                            <div className="text-[10px] text-[#94a3b8] font-bold mt-1.5 ml-5">
                                {getMessage('lastUpdatedLabel')} {new Date(semanticEngineLastUpdated).toLocaleTimeString()}
                            </div>
                        )}

                        <ProgressIndicator
                            visible={isSemanticEngineInitializing}
                            text={semanticEngineInitProgress}
                            showSpinner={true}
                        />

                        <button
                            className="w-full mt-5 flex items-center justify-center gap-2 py-3.5 px-4 bg-[#2563eb] text-white rounded-[12px] font-bold text-[14px] shadow-lg shadow-[#dbeafe] hover:bg-[#1d4ed8] active:scale-[0.98] transition-all disabled:opacity-50"
                            disabled={isSemanticEngineInitializing}
                            onClick={onInitializeSemanticEngine}
                        >
                            <BoltIcon className="w-5 h-5" />
                            <span>{semanticEngineStatus === 'ready' ? getMessage('reinitializeButton') : getMessage('initSemanticEngineButton')}</span>
                        </button>
                    </div>
                </section>

                {/* Model Selection Section */}
                <section>
                    <h3 className="text-[11px] font-[900] text-[#94a3b8] uppercase tracking-[0.1em] mb-2.5 ml-1">{getMessage('embeddingModelLabel')}</h3>

                    <ProgressIndicator
                        visible={(isModelSwitching || isModelDownloading) && progressText !== ''}
                        text={progressText}
                        showSpinner={true}
                    />

                    <div className="flex flex-col gap-3">
                        {availableModels.map(model => (
                            <button
                                key={model.preset}
                                className={`w-full text-left p-4 bg-white border-2 rounded-[16px] transition-all ${currentModel === model.preset
                                        ? 'border-[#3b82f6] bg-[#eff6ff]/50'
                                        : 'border-[#f1f5f9] hover:border-[#cbd5e1]'
                                    } ${isModelSwitching || isModelDownloading ? 'opacity-60 pointer-events-none' : ''}`}
                                onClick={() => !isModelSwitching && !isModelDownloading && onSwitchModel(model.preset)}
                            >
                                <div className="flex justify-between items-start mb-2">
                                    <div className="flex flex-col">
                                        <p className={`text-[14px] font-[800] leading-none ${currentModel === model.preset ? 'text-[#2563eb]' : 'text-[#0f172a]'}`}>{model.preset}</p>
                                        <p className="text-[11px] text-[#64748b] font-medium mt-1.5 leading-snug">
                                            {model.preset === 'multilingual-e5-small' ? getMessage('lightweightModelDescription') : getMessage('betterThanSmallDescription')}
                                        </p>
                                    </div>
                                    {currentModel === model.preset && (
                                        <div className="bg-[#2563eb] text-white rounded-full p-1 scale-75">
                                            <CheckIcon className="w-4 h-4" />
                                        </div>
                                    )}
                                </div>
                                <div className="flex gap-2 pt-1">
                                    <span className="text-[9px] font-bold uppercase px-2 py-0.5 bg-[#f1f5f9] text-[#64748b] rounded-full">{model.performance}</span>
                                    <span className="text-[9px] font-bold uppercase px-2 py-0.5 bg-[#f1f5f9] text-[#64748b] rounded-full">{model.size}</span>
                                    <span className="text-[9px] font-bold uppercase px-2 py-0.5 bg-[#f1f5f9] text-[#64748b] rounded-full">{model.dimension}D</span>
                                </div>
                            </button>
                        ))}
                    </div>
                </section>

                {/* Index Management Section */}
                <section>
                    <h3 className="text-[11px] font-[900] text-[#94a3b8] uppercase tracking-[0.1em] mb-2.5 ml-1">{getMessage('indexDataManagementLabel')}</h3>
                    <div className="grid grid-cols-2 gap-3 mb-4">
                        {[
                            { label: getMessage('indexedPagesLabel'), value: storageStats?.indexedPages || 0, icon: <DocumentIcon className="w-5 h-5" />, color: 'text-violet-600', bg: 'bg-violet-50' },
                            { label: getMessage('indexSizeLabel'), value: formatIndexSize(), icon: <DatabaseIcon className="w-5 h-5" />, color: 'text-emerald-600', bg: 'bg-emerald-50' },
                            { label: getMessage('activeTabsLabel'), value: storageStats?.totalTabs || 0, icon: <TabIcon className="w-5 h-5" />, color: 'text-blue-600', bg: 'bg-blue-50' },
                            { label: getMessage('vectorDocumentsLabel'), value: storageStats?.totalDocuments || 0, icon: <VectorIcon className="w-5 h-5" />, color: 'text-rose-600', bg: 'bg-rose-50' }
                        ].map((stat, i) => (
                            <div key={i} className="bg-white border border-[#f1f5f9] rounded-[16px] p-3 shadow-sm flex flex-col gap-1">
                                <div className="flex justify-between items-center">
                                    <span className="text-[10px] font-bold text-[#94a3b8] uppercase tracking-tight">{stat.label}</span>
                                    <span className={`p-1.5 rounded-[10px] ${stat.bg} ${stat.color}`}>{stat.icon}</span>
                                </div>
                                <span className="text-[18px] font-[900] text-[#0f172a] leading-none mt-1">{stat.value}</span>
                            </div>
                        ))}
                    </div>

                    <button
                        className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-white border border-[#e2e8f0] text-[#64748b] rounded-[12px] font-bold text-[13px] hover:border-red-200 hover:text-red-600 active:scale-[0.98] transition-all"
                        disabled={isClearingData}
                        onClick={onShowClearConfirmation}
                    >
                        <TrashIcon className="w-5 h-5" />
                        <span>{isClearingData ? getMessage('clearingStatus') : getMessage('clearAllDataButton')}</span>
                    </button>
                </section>

                {/* Model Cache Management Section */}
                <ModelCacheManagement
                    cacheStats={cacheStats}
                    isManagingCache={isManagingCache}
                    onCleanupCache={onCleanupCache}
                    onClearAllCache={onClearAllCache}
                />
            </div>
        </div>
    );
};

export default LocalModelPage;
